// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6RhBirhItVrO3wn3liLDL2NVNporf-Ww',
    appId: '1:596703191751:web:33cbfead83e072c572d4e2',
    messagingSenderId: '596703191751',
    projectId: 'moviesapp-3b390',
    authDomain: 'moviesapp-3b390.firebaseapp.com',
    storageBucket: 'moviesapp-3b390.appspot.com',
    measurementId: 'G-2QME5Z8Q7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYoOprax24-_u3ruaNUOUPoestwyL55QQ',
    appId: '1:596703191751:android:6a5167264359181172d4e2',
    messagingSenderId: '596703191751',
    projectId: 'moviesapp-3b390',
    storageBucket: 'moviesapp-3b390.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRbQThSuL4_rAZ64zOFPWrEJogtEs7_XU',
    appId: '1:596703191751:ios:3c5a3424a38a613b72d4e2',
    messagingSenderId: '596703191751',
    projectId: 'moviesapp-3b390',
    storageBucket: 'moviesapp-3b390.appspot.com',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRbQThSuL4_rAZ64zOFPWrEJogtEs7_XU',
    appId: '1:596703191751:ios:3c5a3424a38a613b72d4e2',
    messagingSenderId: '596703191751',
    projectId: 'moviesapp-3b390',
    storageBucket: 'moviesapp-3b390.appspot.com',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6RhBirhItVrO3wn3liLDL2NVNporf-Ww',
    appId: '1:596703191751:web:ca446ba9723d885372d4e2',
    messagingSenderId: '596703191751',
    projectId: 'moviesapp-3b390',
    authDomain: 'moviesapp-3b390.firebaseapp.com',
    storageBucket: 'moviesapp-3b390.appspot.com',
    measurementId: 'G-CBWER5SMGB',
  );
}
